Pylint Spring Cleaning
FuelRats/pipsqueak3 pull request #116
Opened 2019-03-14 22:06 UTC by Eearslya

This PR addresses the majority of pylint's complaints since the recent configuration change.

There are still a few warnings that I left in, mainly the `too-many-branches` warnings, as I feel that these are candidates for refactoring and should not be suppressed.

There is also an issue of `rule.py` redefining the name `rule`, though I'm not sure if this should be fixed or ignored.

2019-03-14 23:22 UTC, shatteredbeam submitted a review, later dismissed
LGTM

2019-03-15 17:39 UTC, theunkn0wn1 requested changes
Looking good for the most part, just a couple small things that should be addressed.

2019-03-15 17:39 UTC, theunkn0wn1 commented on src/packages/commands/rat_command.py
> +_REGISTERED_COMMANDS = {}
registered commands is by no means a constant, as multiple things modify its contents

2019-03-15 17:39 UTC, theunkn0wn1 commented on src/packages/commands/rat_command.py
> +    _REGISTERED_COMMANDS = {}
Since we are modifying this statement anyways in this context we can actually get rid of the global statement.

we can use `_REGISTERED_COMMANDS.clear()` which will get rid of any reason to use the global statement


```py
_REGISTERED_COMMANDS.clear()
```

2019-03-15 18:35 UTC, theunkn0wn1 reviewed
nitpick, with a simple resolution (hopefully)

2019-03-15 18:35 UTC, theunkn0wn1 commented on tests/test_rat_command.py
> +        assert alias.lower() in Commands._registered_commands.keys()
[suggestion] access to `.keys` is redundant. the contains check for dictionary checks against the keys
```suggestion
        assert alias.lower() in Commands._registered_commands
```

2019-03-15 18:38 UTC, theunkn0wn1 approved these changes

2019-03-15 18:43 UTC, shatteredbeam approved these changes

2019-03-15 18:44 UTC, merged