[SPARK-136] Refactor "RatMama" test suite
FuelRats/pipsqueak3 pull request #137
Opened 2019-04-10 23:25 UTC by Eearslya

Refactor and simplify the ratmama test suite, bringing the test count down from 900+ to just 12. This approach also avoids much of the monkeypatching required, reducing the risk of a refactor rendering these tests inoperable.

2019-04-11 05:11 UTC, theunkn0wn1 reviewed
Overall its looking great! thanks for writing this.

Two small things i would like to see addressed prior to merging this 🙂

2019-04-11 05:11 UTC, theunkn0wn1 commented on tests/fixtures/mock_bot.py
> +                "realname": "RatMama"
[style] stray newline in data

2019-04-11 05:11 UTC, theunkn0wn1 commented on tests/unit/test_ratmama.py
> +                                             "while a dispatch is underway.")
[error] while i recognize this wasn't added by you, can you please adjust this test and the underlying implementation as to match the mecha2 interface while we are here?
```
<unknown> drillsignal ki pc
<Drillsqueak[BOT]> unknown: You already sent a Signal! Please stand by, someone will help you soon!
```

2019-04-11 15:53 UTC, theunkn0wn1 requested changes

2019-04-11 15:53 UTC, theunkn0wn1 commented on src/packages/ratmama/ratmama_parser.py
> +            await ctx.reply(f"{ctx.user.nickname}: You already sent a Signal! Please stand by,"
[error] *squint* doesn't `ctx.reply` already embed the nickname into the message stream?

2019-04-11 15:59 UTC, theunkn0wn1 approved these changes
LGTM

2019-04-12 21:25 UTC, shatteredbeam approved these changes
You did a ton of work on improving this,  Looks great.

2019-04-12 21:28 UTC, theunkn0wn1 commented
Update and this will be merged

2019-04-12 21:32 UTC, merged