Core Commands, First pass.
FuelRats/pipsqueak3 pull request #165
Opened 2019-12-21 06:44 UTC by shatteredbeam

First draft for core case commands.

There WILL be missing items, and possibly incorrect methods.  Thus far methods/interaction have been very liquid throughout the writing process.

See case_management.py.

There are currently no tests.

2019-12-21 08:21 UTC, theunkn0wn1 requested changes
First pass.

2019-12-21 08:21 UTC, theunkn0wn1 commented on src/commands/__init__.py
> +from . import deletion_management
[error] please add these to the `__all__` on l15 to avoid linting warnings (and possible PyC auto-import optimizations)

2019-12-21 08:21 UTC, theunkn0wn1 commented on src/commands/case_management.py
> +from src.packages.utils import Platforms, Status
I think we can get away with `from ..packagages` here, make it easier when we inevidibly change project structure again...

2019-12-21 08:21 UTC, theunkn0wn1 commented on src/commands/case_management.py
> +_TIME_RE = re.compile('(\d+)[: ](\d+)')
[suggestion] regex strings should always be `r""` to avoid unintentional python escape sequences

2019-12-21 08:21 UTC, theunkn0wn1 commented on src/commands/case_management.py
> +            rescue = ctx.bot.board.get(ctx.words[1])
[suggestion] else block can be simplified by returning Rescue right away

2019-12-21 08:21 UTC, theunkn0wn1 commented on src/commands/case_management.py
> +    Permission: Rat
[question] (maintainability) I question the value of these docstrings when these are defined only a couple lines above in decorators?

2019-12-21 08:21 UTC, theunkn0wn1 commented on src/commands/case_management.py
> +
missing TODO to verify first limpet, as it must go to a identified, assigned rat.

2019-12-21 08:21 UTC, theunkn0wn1 commented on src/commands/case_management.py
> +        del ctx.bot.board[requested_case]
```py

    async def remove_rescue(self, target: BoardKey):
        """ removes a rescue from active tracking """
```

2019-12-21 08:21 UTC, theunkn0wn1 commented on src/commands/case_management.py
> +    # if that changes.
[suggestion] emit a deprication warning 😉 
```suggestion
    # if that changes.
    warnings.warn("This command is a deprecated artefact", DeprecationWarning)
```

2019-12-21 08:21 UTC, theunkn0wn1 commented on src/commands/case_management.py
> +        async with ctx.bot.board.create_rescue() as case:
[error] `RatBoard.create_rescue` is not a context manager any more

2019-12-21 08:21 UTC, theunkn0wn1 commented on src/commands/case_management.py
> +    if not rescue:
[suggestion] the Truthy branch of this logic is simpler, consider inverting this statement to reduce the number of lines within the indented block. (change to `if rescue` and put 313->317 inside the indented block. put the current indented block unidented.)

2019-12-21 08:21 UTC, theunkn0wn1 commented on src/commands/case_management.py
> +        await ctx.reply("Caution: IRC Nickname does not match CMDR Name.")
[suggestion] log this event.

2019-12-21 08:21 UTC, theunkn0wn1 commented on src/commands/case_management.py
> +                                                            detailed=False, max_units=2) + " ago"
[error] string concatenation

2019-12-27 18:47 UTC, Eearslya commented on src/commands/case_management.py
> +    # if that changes.
I'm not so sure a log message warning of a deprecated command is very useful.. We've already got the IRC reply, what does logging do for those who look at the logs?

2019-12-27 19:04 UTC, Eearslya commented on src/commands/case_management.py
> +            last_message = ctx.bot.last_user_message[rescue.client.casefold()]
[Question] Should this not use `irc_nickname`, if available?

2019-12-27 19:04 UTC, Eearslya commented on src/commands/case_management.py
> +    created_timestamp = rescue.updated_at.strftime("%b %d %H:%M:%S UTC")
[Suggestion] Duplicated code to generate quote, suggest moving to private method.

2019-12-27 19:04 UTC, Eearslya commented on src/commands/case_management.py
> +    rescue_client = rescue.irc_nickname if rescue.irc_nickname else rescue.client
[Error] Unused variable

2019-12-27 19:04 UTC, Eearslya commented on src/commands/case_management.py
> +        case.platform = Platforms.PC
[Error]
```suggestion
        case.platform = Platforms.XB
```

2019-12-27 19:04 UTC, Eearslya commented on src/commands/deletion_management.py
> +def _validate(ctx: Context, validate: str) -> Optional[Rescue]:
[Suggestion] Duplicate from `case_management.py`. Maybe a method in `RatBoard` instead?

2019-12-27 20:39 UTC, theunkn0wn1 commented on src/commands/case_management.py
> +_TIME_RE = re.compile('(\d+)[: ](\d+)')
[suggestion] please document what the heck this is doing. some of us can't read regex :(

2019-12-27 20:39 UTC, theunkn0wn1 commented on src/commands/case_management.py
> +        del ctx.bot.board[requested_case]
```suggestion
        await ctx.bot.board.remove_rescue(requested_case)
```

2019-12-27 20:39 UTC, theunkn0wn1 commented on src/commands/case_management.py
> +    # if that changes.
tells whoever is managing the logs that a depricated command was called, which is probably a problem.

2019-12-27 20:39 UTC, theunkn0wn1 commented on src/commands/debug.py
> +    await context.reply(f"Client: {debug_rescue.client}    System: {debug_rescue.system}")
[question] whats up with the excess whitespace in this routine?
if you are trying to space things out please use the string formatting tools. e.g. `{debug_rescue.client: <20}` to left-justify the interpolated string into 20 character width, using spaces as padding.
```py
In [8]: f"{data: <20}"
Out[8]: '21                  '
```

2020-06-15 04:14 UTC, closed without merging

2020-06-15 04:15 UTC, theunkn0wn1 commented
I believe everything here has already been merged in #175, closing now as housekeeping.